<?php

return [
    'accordion' => [
        'name' => 'Accordion',
        'category' => 'disclosure',
        'tag' => '<x-sampaui::accordion />',
        'props' => ['items', 'multiple'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::accordion :items="$items" />',
        'livewire' => 'Preserva atributos wire:* no elemento raiz.',
    ],
    'alert' => [
        'name' => 'Alert',
        'category' => 'feedback',
        'tag' => '<x-sampaui::alert />',
        'props' => ['variant', 'type', 'title', 'icon', 'dismissible'],
        'slots' => ['default'],
        'variants' => ['success', 'danger', 'error', 'warning', 'info'],
        'example' => '<x-sampaui::alert variant="success" title="Salvo">Alteracoes publicadas.</x-sampaui::alert>',
        'livewire' => 'Pode ser exibido condicionalmente por estado Livewire.',
    ],
    'avatar' => [
        'name' => 'Avatar',
        'category' => 'media',
        'tag' => '<x-sampaui::avatar />',
        'props' => ['src', 'alt', 'name', 'size'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::avatar name="Ana Souza" />',
        'livewire' => 'Componente visual estatico, seguro em renders Livewire.',
    ],
    'avatar-upload' => [
        'name' => 'Avatar Upload',
        'category' => 'form',
        'tag' => '<x-sampaui::avatar-upload />',
        'props' => ['name', 'label', 'src', 'alt', 'accept'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::avatar-upload name="avatar" label="Foto" wire:model="avatar" />',
        'livewire' => 'Use com wire:model para uploads do Livewire.',
    ],
    'badge' => [
        'name' => 'Badge',
        'category' => 'feedback',
        'tag' => '<x-sampaui::badge />',
        'props' => ['variant', 'size', 'icon'],
        'slots' => ['default'],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted', 'light'],
        'example' => '<x-sampaui::badge variant="accent">Novo</x-sampaui::badge>',
        'livewire' => 'Pode receber textos e estados calculados pelo Livewire.',
    ],
    'brand-mark' => [
        'name' => 'Brand Mark',
        'category' => 'navigation',
        'tag' => '<x-sampaui::brand-mark />',
        'props' => ['label', 'href', 'icon'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::brand-mark label="SampaUI" href="/" />',
        'livewire' => 'Aceita wire:navigate quando usado como link.',
    ],
    'breadcrumb' => [
        'name' => 'Breadcrumb',
        'category' => 'navigation',
        'tag' => '<x-sampaui::breadcrumb />',
        'props' => ['items'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::breadcrumb :items="$items" />',
        'livewire' => 'Links podem usar wire:navigate nos itens.',
    ],
    'button' => [
        'name' => 'Button',
        'category' => 'action',
        'tag' => '<x-sampaui::button />',
        'props' => ['variant', 'size', 'icon', 'icon-position', 'href', 'rounded', 'loading', 'disabled', 'full'],
        'slots' => ['default'],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted', 'light', 'outline', 'ghost'],
        'example' => '<x-sampaui::button variant="primary" icon="plus" wire:click="save">Salvar</x-sampaui::button>',
        'livewire' => 'Preserva wire:click, wire:navigate e demais atributos no elemento interativo real.',
    ],
    'card' => [
        'name' => 'Card',
        'category' => 'surface',
        'tag' => '<x-sampaui::card />',
        'props' => ['title', 'description', 'variant'],
        'slots' => ['default', 'footer', 'actions'],
        'variants' => ['default', 'muted', 'primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple'],
        'example' => '<x-sampaui::card title="Resumo">Conteudo do card.</x-sampaui::card>',
        'livewire' => 'Superficie segura para conteudo reativo renderizado pelo Livewire.',
    ],
    'cep' => [
        'name' => 'CEP',
        'category' => 'form',
        'tag' => '<x-sampaui::cep />',
        'props' => ['label', 'name', 'placeholder', 'icon'],
        'slots' => ['prefix', 'suffix'],
        'variants' => [],
        'example' => '<x-sampaui::cep name="postal_code" label="CEP" wire:model.live="postal_code" />',
        'livewire' => 'Formata internamente 12345678 como 12345-678 e nao depende de plugin externo de mascara.',
    ],
    'checkbox' => [
        'name' => 'Checkbox',
        'category' => 'form',
        'tag' => '<x-sampaui::checkbox />',
        'props' => ['name', 'label', 'value', 'checked', 'disabled', 'color'],
        'slots' => ['default'],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted'],
        'example' => '<x-sampaui::checkbox name="terms" label="Aceito os termos" wire:model="terms" />',
        'livewire' => 'Use wire:model diretamente no input real.',
    ],
    'command-palette' => [
        'name' => 'Command Palette',
        'category' => 'overlay',
        'tag' => '<x-sampaui::command-palette />',
        'props' => ['items', 'placeholder', 'open'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::command-palette :items="$items" />',
        'livewire' => 'Pode disparar navegacao ou acoes via eventos do browser.',
    ],
    'currency-br' => [
        'name' => 'Currency BR',
        'category' => 'form',
        'tag' => '<x-sampaui::currency-br />',
        'props' => ['label', 'name', 'placeholder', 'symbol', 'icon'],
        'slots' => ['prefix', 'suffix'],
        'variants' => [],
        'example' => '<x-sampaui::currency-br name="price" label="Valor" wire:model.live="price" />',
        'livewire' => 'Formata valores no padrao brasileiro e sincroniza o model Alpine/Livewire.',
    ],
    'date-picker' => [
        'name' => 'DatePicker',
        'category' => 'form',
        'tag' => '<x-sampaui::date-picker />',
        'props' => ['name', 'label', 'value', 'min', 'max', 'clearable', 'disabled', 'error'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::date-picker name="scheduled_at" label="Data" wire:model.live="scheduledAt" />',
        'livewire' => 'Usa x-modelable e preserva wire:model.',
    ],
    'drawer' => [
        'name' => 'Drawer',
        'category' => 'overlay',
        'tag' => '<x-sampaui::drawer />',
        'props' => ['name', 'title', 'description', 'placement', 'variant', 'open'],
        'slots' => ['default', 'footer'],
        'variants' => ['default', 'muted', 'primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple'],
        'example' => '<x-sampaui::drawer name="filters" title="Filtros">Conteudo</x-sampaui::drawer>',
        'livewire' => 'Controle abertura via Alpine ou eventos disparados por Livewire.',
    ],
    'dropdown' => [
        'name' => 'Dropdown',
        'category' => 'overlay',
        'tag' => '<x-sampaui::dropdown />',
        'props' => ['align', 'width'],
        'slots' => ['trigger', 'default'],
        'variants' => [],
        'example' => '<x-sampaui::dropdown><x-slot:trigger>Menu</x-slot:trigger>Conteudo</x-sampaui::dropdown>',
        'livewire' => 'Itens internos podem usar wire:click ou wire:navigate.',
    ],
    'dropdown-item' => [
        'name' => 'Dropdown Item',
        'category' => 'overlay',
        'tag' => '<x-sampaui::dropdown-item />',
        'props' => ['href', 'icon', 'danger', 'disabled'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::dropdown-item icon="pencil" wire:click="edit">Editar</x-sampaui::dropdown-item>',
        'livewire' => 'Preserva wire:click no item interativo.',
    ],
    'empty-state' => [
        'name' => 'Empty State',
        'category' => 'feedback',
        'tag' => '<x-sampaui::empty-state />',
        'props' => ['title', 'description', 'icon'],
        'slots' => ['default', 'actions'],
        'variants' => [],
        'example' => '<x-sampaui::empty-state title="Nada encontrado" icon="inbox" />',
        'livewire' => 'Use em estados condicionais de listas Livewire.',
    ],
    'file-upload' => [
        'name' => 'File Upload',
        'category' => 'form',
        'tag' => '<x-sampaui::file-upload />',
        'props' => ['name', 'label', 'accept', 'multiple', 'preview', 'disabled', 'error'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::file-upload name="contract" label="Contrato" wire:model="contract" />',
        'livewire' => 'Use com o recurso de upload de arquivos do Livewire.',
    ],
    'header' => [
        'name' => 'Header',
        'category' => 'layout',
        'tag' => '<x-sampaui::header />',
        'props' => ['title', 'subtitle', 'eyebrow', 'status', 'menu'],
        'slots' => ['actions'],
        'variants' => [],
        'example' => '<x-sampaui::header title="Clientes"><x-slot:actions>Acoes</x-slot:actions></x-sampaui::header>',
        'livewire' => 'Acoes internas podem chamar metodos Livewire.',
    ],
    'indicator' => [
        'name' => 'Indicator',
        'category' => 'feedback',
        'tag' => '<x-sampaui::indicator />',
        'props' => ['variant', 'pulse', 'label'],
        'slots' => [],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted', 'light'],
        'example' => '<x-sampaui::indicator variant="success" label="Online" />',
        'livewire' => 'Bom para estados calculados de disponibilidade.',
    ],
    'input' => [
        'name' => 'Input',
        'category' => 'form',
        'tag' => '<x-sampaui::input />',
        'props' => ['type', 'label', 'name', 'value', 'placeholder', 'error', 'disabled', 'icon', 'revealable'],
        'slots' => ['prefix', 'suffix'],
        'variants' => [],
        'example' => '<x-sampaui::input name="email" label="Email" icon="envelope" wire:model.live="email" />',
        'livewire' => 'wire:model fica no input real e nao exige prop value.',
    ],
    'modal' => [
        'name' => 'Modal',
        'category' => 'overlay',
        'tag' => '<x-sampaui::modal />',
        'props' => ['name', 'title', 'description', 'open', 'size'],
        'slots' => ['default', 'footer'],
        'variants' => [],
        'example' => '<x-sampaui::modal name="confirm" title="Confirmar">Conteudo</x-sampaui::modal>',
        'livewire' => 'Pode abrir por eventos e conter forms Livewire.',
    ],
    'pagination' => [
        'name' => 'Pagination',
        'category' => 'navigation',
        'tag' => '<x-sampaui::pagination />',
        'props' => ['current-page', 'last-page', 'total', 'per-page', 'wire-method'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::pagination :current-page="1" :last-page="8" wire-method="gotoPage" />',
        'livewire' => 'Pode chamar metodo Livewire definido em wire-method.',
    ],
    'phone' => [
        'name' => 'Phone',
        'category' => 'form',
        'tag' => '<x-sampaui::phone />',
        'props' => ['label', 'name', 'placeholder', 'icon'],
        'slots' => ['prefix', 'suffix'],
        'variants' => [],
        'example' => '<x-sampaui::phone name="phone" label="Telefone" wire:model.live="phone" />',
        'livewire' => 'Formata telefone brasileiro internamente e sincroniza o model Alpine/Livewire.',
    ],
    'pin' => [
        'name' => 'Pin',
        'category' => 'form',
        'tag' => '<x-sampaui::pin />',
        'props' => ['name', 'label', 'length', 'numbers', 'letters', 'clear', 'smart', 'disabled', 'error'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::pin name="code" label="Codigo" length="6" numbers wire:model.live="code" />',
        'livewire' => 'Suporta x-modelable e sincronizacao bidirecional com Livewire.',
    ],
    'progress' => [
        'name' => 'Progress',
        'category' => 'feedback',
        'tag' => '<x-sampaui::progress />',
        'props' => ['value', 'max', 'variant', 'label'],
        'slots' => [],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted', 'light'],
        'example' => '<x-sampaui::progress value="60" variant="primary" />',
        'livewire' => 'Valor pode ser atualizado por propriedades Livewire.',
    ],
    'radio' => [
        'name' => 'Radio',
        'category' => 'form',
        'tag' => '<x-sampaui::radio />',
        'props' => ['name', 'label', 'value', 'options', 'inline', 'checked', 'disabled', 'color'],
        'slots' => [],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted'],
        'example' => '<x-sampaui::radio name="status" :options="[\'active\' => \'Ativo\']" wire:model="status" />',
        'livewire' => 'Use wire:model para vincular a opcao selecionada.',
    ],
    'select' => [
        'name' => 'Select',
        'category' => 'form',
        'tag' => '<x-sampaui::select />',
        'props' => ['name', 'label', 'value', 'options', 'placeholder', 'empty-text', 'error', 'disabled', 'required'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::select name="status" label="Status" :options="[\'active\' => \'Ativo\']" wire:model.live="status" />',
        'livewire' => 'Usa x-modelable e sincroniza com um select real oculto para formularios.',
    ],
    'select-multiple' => [
        'name' => 'Select Multiple',
        'category' => 'form',
        'tag' => '<x-sampaui::select-multiple />',
        'props' => ['name', 'label', 'placeholder', 'options', 'selected', 'disabled', 'loading', 'error'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::select-multiple name="roles" label="Perfis" :options="$roles" wire:model.live="roles" />',
        'livewire' => 'Sincroniza array de valores com Livewire.',
    ],
    'select-search' => [
        'name' => 'Select Search',
        'category' => 'form',
        'tag' => '<x-sampaui::select-search />',
        'props' => ['name', 'label', 'placeholder', 'options', 'value', 'disabled', 'loading', 'error'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::select-search name="owner" label="Responsavel" :options="$owners" wire:model.live="owner" />',
        'livewire' => 'Usa x-modelable e preserva wire:model para busca local.',
    ],
    'sidebar' => [
        'name' => 'Sidebar',
        'category' => 'navigation',
        'tag' => '<x-sampaui::sidebar />',
        'props' => ['brand', 'brand-href', 'items', 'user', 'initial-state'],
        'slots' => ['logo', 'footer'],
        'variants' => [],
        'example' => '<x-sampaui::sidebar brand="SampaUI" :items="$items" />',
        'livewire' => 'Itens podem usar wire:navigate.',
    ],
    'skeleton' => [
        'name' => 'Skeleton',
        'category' => 'feedback',
        'tag' => '<x-sampaui::skeleton />',
        'props' => ['lines', 'avatar'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::skeleton lines="3" />',
        'livewire' => 'Use com wire:loading para estados de carregamento.',
    ],
    'stepper' => [
        'name' => 'Stepper',
        'category' => 'navigation',
        'tag' => '<x-sampaui::stepper />',
        'props' => ['steps', 'current'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::stepper :steps="$steps" :current="2" />',
        'livewire' => 'Passos podem refletir estado de formulario Livewire.',
    ],
    'tab-panel' => [
        'name' => 'Tab Panel',
        'category' => 'navigation',
        'tag' => '<x-sampaui::tab-panel />',
        'props' => ['name'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::tab-panel name="details">Detalhes</x-sampaui::tab-panel>',
        'livewire' => 'Conteudo interno pode ser Livewire.',
    ],
    'table' => [
        'name' => 'Table',
        'category' => 'data',
        'tag' => '<x-sampaui::table />',
        'props' => ['columns', 'rows', 'empty', 'sort-by', 'sort-direction', 'sort-method'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::table :columns="$columns" :rows="$rows" />',
        'livewire' => 'Linhas, colunas e ordenacao podem vir de propriedades computadas do Livewire.',
    ],
    'tabs' => [
        'name' => 'Tabs',
        'category' => 'navigation',
        'tag' => '<x-sampaui::tabs />',
        'props' => ['tabs', 'active'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::tabs :tabs="$tabs" active="overview" />',
        'livewire' => 'Pode controlar a aba ativa via estado Alpine/Livewire.',
    ],
    'textarea' => [
        'name' => 'Textarea',
        'category' => 'form',
        'tag' => '<x-sampaui::textarea />',
        'props' => ['name', 'label', 'rows', 'placeholder', 'error', 'disabled'],
        'slots' => [],
        'variants' => [],
        'example' => '<x-sampaui::textarea name="notes" label="Observacoes" wire:model.live="notes" />',
        'livewire' => 'wire:model fica no textarea real.',
    ],
    'toast' => [
        'name' => 'Toast',
        'category' => 'feedback',
        'tag' => '<x-sampaui::toast />',
        'props' => ['position'],
        'slots' => [],
        'variants' => ['success', 'danger', 'warning', 'info'],
        'example' => '<x-sampaui::toast />',
        'livewire' => 'Dispare CustomEvent("toast") pelo browser a partir de acoes Livewire.',
    ],
    'toggle' => [
        'name' => 'Toggle',
        'category' => 'form',
        'tag' => '<x-sampaui::toggle />',
        'props' => ['name', 'label', 'checked', 'disabled', 'color'],
        'slots' => [],
        'variants' => ['primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info', 'purple', 'muted', 'light'],
        'example' => '<x-sampaui::toggle name="active" label="Ativo" color="accent" wire:model="active" />',
        'livewire' => 'wire:model fica no checkbox real.',
    ],
    'tooltip' => [
        'name' => 'Tooltip',
        'category' => 'overlay',
        'tag' => '<x-sampaui::tooltip />',
        'props' => ['text', 'placement'],
        'slots' => ['default'],
        'variants' => [],
        'example' => '<x-sampaui::tooltip text="Ajuda"><x-sampaui::button icon="question" /></x-sampaui::tooltip>',
        'livewire' => 'Componente visual, seguro em re-renderizacoes.',
    ],
];
